language: node_js

node_js: stable

cache:
    apt: true
    directories:
        - node_modules

notifications:
    email:
        recipients:
            - cnine229@qq.com
        on_success: change
        on_failure: always

env:
    global:
        # Github Pages
        - GH_REF: github.com/Aysnine/aysnine.github.io.git
        - GH_CUSTOM_DOMAIN: old.cnine.me

branches:
  only:
  - master

before_install:
    - export TZ='Asia/Shanghai'
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - chmod +x ./deploy.sh

script:
  - yarn docs:build

after_script:
  - ./deploy.sh
