language: node_js
node_js: stable

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - ./deploy.sh

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
