menu:
    HOME: /
    Archive: /archives/
    GitHub: https://github.com/Aysnine
    RSS: atom.xml

favicon: /cnine.png
logo: /cnine.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
